sonar.projectKey=for2proj_bookswap
sonar.organization=for2proj
sonar.projectName=BookSwap
sonar.projectVersion=1.0.0

# Source and test directories
sonar.sources=backend/app
sonar.tests=backend/tests
sonar.python.version=3.12

# Coverage and test reports
sonar.python.coverage.reportPaths=backend/reports/coverage.xml
sonar.python.xunit.reportPath=backend/reports/junit.xml

# Exclusions
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/node_modules/**,**/htmlcov/**,**/.git/**,**/alembic/**

# Quality Gate
sonar.qualitygate.wait=true

# Language
sonar.language=py
